### ISSUE TITLE
Most exports are missing

### ISSUE THREAD

**Issue by bschilder** [praneet1988/ELeFHAnt#2]
If you don't explicitly call from a package with `package::function` notation, you need to do at least one of the following: 

1. export the necessary functions using the syntax `@export Seurat DefaultAssay` in the roxygen documentation.
2. export the entire package `@export Seurat`.
3. manually add `Seurat` to the NAMESPACE file.
 

Otherwise, it gives the user errors like this when Seurat hasn't been loaded yet:

` DefaultAssay(x) <- "RNA" : could not find function "DefaultAssay<-`

**Comment by bschilder** [comment]
A similar problem arises with whatever package "stratified" is from:

```R
Error in stratified(scaled_data, group = "Clusters", size = 0.6, bothSets = TRUE) : 
  could not find function "stratified"
```

**Comment by bschilder** [comment]
Managed to run all the way through the following after getting stuck at each step that was missing an export, finding the package it's from, and then loading that package. 


```R
library(scNLP) # remotes::install_github('neurogenomics/scNLP')

# BiocManager::install("fgsea")
library(ELeFHAnt) # remotes::install_github('praneet1988/ELeFHAnt')
### Must load these first until they are added to ELeFHAnt exports
### library(pkg) # missing_function
library(Seurat) # (many functions)
library(splitstackshape) # stratified
library(randomForest) # randomForest
library(e1071) # svm
library(tibble) # deframe
library(fgsea) # fgsea

obj <- scNLP::pseudo_seurat
obj$Celltypes <- obj$celltype
obj <- subset(obj, batch %in% c("LaManno2020","Raj2020"))
seurat_list <- Seurat::SplitObject(obj, split.by = "batch")

seurat_integrated <- ELeFHAnt::LabelHarmonization(seurat.objects   = seurat_list, 
                                                  classification.method = "randomForest")
```

**Comment by praneet1988** [comment]
Dear Brian,
Thank you so much for pointing us this issue. Are you facing this issue even after installing the package using install_github?
All the package dependencies are mentioned in DESCRIPTION File and install should install all of them and load them when loading the library(ELeFHAnt).
Can you please confirm?

**Comment by praneet1988** [comment]
When I removed the package and installed again it automatically load all the required packages.
library(ELeFHAnt)
#> Loading required package: Seurat
#> Attaching SeuratObject
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> Loading required package: tidyr
#> Loading required package: kernlab
#> Loading required package: dbscan
#> Loading required package: randomForest
#> randomForest 4.6-14
#> Type rfNews() to see new features/changes/bug fixes.
#> 
#> Attaching package: 'randomForest'
#> The following object is masked from 'package:dplyr':
#> 
#>     combine
#> Loading required package: caTools
#> Loading required package: e1071
#> Loading required package: ggplot2
#> 
#> Attaching package: 'ggplot2'
#> The following object is masked from 'package:randomForest':
#> 
#>     margin
#> The following object is masked from 'package:kernlab':
#> 
#>     alpha
#> Loading required package: class
#> Loading required package: splitstackshape
#> Loading required package: fgsea
#> Loading required package: tibble

**Comment by bschilder** [comment]
Thanks for the quick reply. I actually installed via `install_github` originally.

`library(ELeFHAnt)` does indeed load the necessary deps. 

The reason they weren't loading in my case was bc i had restarted R at some point (unloading ELeFHAnt), and then called `ELeFHAnt::LabelHarmonization` without rerunning `library(ELeFHAnt)`. In these situations the deps  don't get loaded. I think adding these as @exports in each function (or for the entire packages) would resolve this.

This may not be an issue for most users but in my case I'm actually trying to integrate`ELeFHAnt` into `scNLP`, in which case avoiding within-function `library` calls is a CRAN requirement.

**Comment by praneet1988** [comment]
Dear Brian,
I have now added imports (all required dependencies) for each function. This should resolve the issue. Please let me know if you face any issues. 
I checked your package (scNLP) out. Amazing work!
Have a wonderful day.

**Comment by bschilder** [comment]
Thanks so much @praneet1988! I think `ELeFHAnt` will be a great addition to scNLP.
