### ISSUE TITLE
Let users select which metadata columns contains celltype identity

### ISSUE THREAD

**Issue by bschilder** [praneet1988/ELeFHAnt#3]
`LabelHarmonization` currently expects the cell-type labels are stored in the metadata column `Celltypes`. 
Would be good to let users specify the column name as an argument bc not everyone will use that exact name:

e.g.: 
`LabelHarmonization(celltype_col="celltype_label")`

**Comment by praneet1988** [comment]
Dear Brian,
This is something we have planned out for our next release. However, we will be adding this functionality in ELeFHAntdev (https://github.com/praneet1988/ELeFHAntdev) soon.
Hope this helps.

You are welcome to contribute to the code. Please open a pull request if you have any suggested improvements.

Have a wonderful day.

**Comment by bschilder** [comment]
Sounds great, thanks!
