### ISSUE TITLE
Control celltype naming reference

### ISSUE THREAD

**Issue by bschilder** [praneet1988/ELeFHAnt#4]
Hello, 

I was wondering if there was a way to control which dataset is used when deciding on a label for each cluster.

In my case, I'm integrating several datasets with varying quality of annotations. Ideally, I'd like to map them all onto the controlled ontology used by the HPCA dataset. Is there a way I can set this?

![ensemble](https://user-images.githubusercontent.com/34280215/126772986-bc82494c-0086-45b1-b91a-240ac7bb5cca.png)

## Reprex

```R
library(scNLP) # remotes::install_github('neurogenomics/scNLP')
obj <- scNLP::pseudo_seurat
obj$Celltypes <- obj$celltype
obj <- subset(obj, batch %in% c("LaManno2020","Raj2020","Aerts2020"))
seurat_list <- Seurat::SplitObject(obj, split.by = "batch") 

dplyr::group_by(obj@meta.data, batch) %>% dplyr::count()
remove(obj)


library(SingleCellExperiment)
library(celldex) # BiocManager::install("celldex")
hpca_se = celldex::HumanPrimaryCellAtlasData() 
SummarizedExperiment:::assay(hpca_se,"counts") <-  exp(SummarizedExperiment:::assay(hpca_se))

hpca_seurat <- scKirby::ingest_data(obj = as(hpca_se,"SingleCellExperiment"),
                                              output_type = "seurat", 
                                              save_output = FALSE)
hpca_seurat$Celltypes <- hpca_seurat$label.fine
hpca_seurat$batch <- "HPCA"
hpca_seurat$dataset <- "HPCA"
hpca_seurat$species <- "human"
#### Subset to only genes in seurat_list
hpca_seurat <- hpca_seurat[rownames(seurat_list[[1]]),]

seurat_list[["HPCA"]] <- SeuratObject::RenameAssays(object = hpca_seurat, originalexp="RNA") 
remove(hpca_se, hpca_seurat)


library(ELeFHAnt) # remotes::install_github('praneet1988/ELeFHAnt') 

seurat_integrated <- ELeFHAnt::LabelHarmonization(seurat.objects = seurat_list, 
                                                  classification.method = "Ensemble", 
                                                  downsample = T)
```

Many thanks, 
Brian

**Comment by praneet1988** [comment]
Dear Brian,
Hope you are well. Currently, ELeFHAnt's Label Transfer doesn't restrict to one dataset cell type annotations for harmonizing cell types across integrated clusters. It learns all incoming cell types from all datasets to then harmonize cell types. However, there is a work around for using standard annotations for harmonization (in your case using HPCA dataset).

Here is what I propose:
1) Integrate datasets using Seurat Integration and obtain integrated clusters. Let's say integrated object is integrated.atlas
2) Set DefaultAssay(integrated.atlas) = "RNA"
3) Prepare HPCA dataset for cell type annotation.  DefaultAssay(HPCA) = "RNA" and HPCA$Celltypes = HPCA$celltypecolumn [please set according to dataset]
4) Run CelltypeAnnotation. out.ELeFHAnt = CelltypeAnnotation(reference = HPCA, query = integrated.atlas, downsample = TRUE, downsample_to = 200, classification.method = "Ensemble", crossvalidationSVM = 10, validatePredictions = FALSE, selectvarfeatures = 2000)
5) DefaultAssay(out.ELeFHAnt) <- "integrated"
6) Plot using DimPlot. DimPlot(out.ELeFHAnt, group.by = "PredictedCelltype_UsingEnsemble", label=T, repel=T) + NoLegend()

Hope this helps. Please let me know if you have any questions.

Have a wonderful day.
Best,
Praneet

**Comment by praneet1988** [comment]
A quick suggestion. As I see you have datasets coming from different species please set features of all datasets to Human Gene symbols or ids so that while finding variable features or anchors gene are consistent. You can use Ensemble biomart for finding human orthologs or another trick is to convert feature names (GeneSymbols) to Uppercase for all datasets.

**Comment by praneet1988** [comment]
Dear Brian,
Hope our suggestions helped you. Please let us know if you have any questions or face any issues.
V1.1.1 is coming on Monday (August 2) so please do check it out. It has improved Cell type Annotation function (ability to annotate cells and decide for approximation if reference is smaller than query).

Have a wonderful weekend.
