### ISSUE TITLE
seurat_clusters present but not being recognized by the function CelltypeAnnotation

### ISSUE THREAD

**Issue by Rohit-Satyam** [praneet1988/ELeFHAnt#5]
Hi I have a single reference atlas "Malaria Cell Atlas" and I was trying to use your package to transfer labels from the reference to query.

You can see in screenshot below that even though I have `seurat_clusters` column in my reference Seurat object, I still get the error

```r
Error: Cannot find 'seurat_clusters' in this Seurat object
``` 
Kindly help!! Also since I have only one Dataset as reference do I need to perform `LabelHarmonization` as well??

![image](https://user-images.githubusercontent.com/55479480/163382891-e20c8701-d3f9-4012-b7e8-80c4d94a0e06.png)

**Comment by praneet1988** [comment]
Dear Rohit,
Hope you are well. First of all, thank you so much for trying ELeFHAnt out. We look forward to your feedback.

Regarding the error, ELeFHAnt is searching for seurat_clusters column in the query. Have you processed your query data using Seurat to find clusters? Also, in the reference, you need column Celltypes for it to perform learning on. 

Label Harmonization is recommended when you are integrating multiple  reference atlases.

Hope this helps.

Best,
Praneet

**Comment by praneet1988** [comment]
Dear Rohit,
I hope the solution worked. I am closing the issue. Please feel free to re-open in case you still the problem.
